from typing import Any

import requests
import streamlit as st


def normalize_base_url(base_url: str) -> str:
    cleaned = base_url.strip()
    if not cleaned:
        return "http://127.0.0.1:8005"
    if cleaned.startswith("http://") or cleaned.startswith("https://"):
        return cleaned.rstrip("/")
    return f"http://{cleaned.rstrip('/')}"


def call_answer(base_url: str, query: str, limit: int = 8, semantic: bool = True) -> dict[str, Any]:
    url = f"{normalize_base_url(base_url)}/answer"
    payload = {"query": query, "limit": limit, "semantic": semantic}
    response = requests.post(url, json=payload, timeout=60)
    response.raise_for_status()
    return response.json()

st.set_page_config(page_title="Procurement KG Assistant", page_icon="📚", layout="wide")
st.title("Procurement KG Assistant")

with st.sidebar:
    st.header("Connection")
    base_url = st.text_input("API base URL", value="http://127.0.0.1:8000")
    st.caption("Use the same host and port as your FastAPI server.")
    if st.button("Check backend"):
        try:
            health = requests.get(f"{normalize_base_url(base_url)}/health", timeout=10).json()
            st.success("Backend reachable")
            st.json(
                {
                    "retrieval_profile": health.get("retrieval_profile"),
                    "embedding_model": health.get("embedding_model"),
                    "embedding_input_version": health.get("embedding_input_version"),
                    "vector_index": health.get("vector_index"),
                    "answering_configured": health.get("answering_configured"),
                }
            )
        except Exception as exc:
            st.error(f"Backend unreachable: {exc}")

query = st.text_area(
    "Your question",
    value="Does the Procurement Act 2023 require a contracting authority to award a contract to the lowest-priced tender?",
    height=120,
)
limit = st.number_input(
    "Evidence passages to retrieve",
    min_value=1,
    max_value=40,
    value=16,
    help="How many retrieved nodes are passed to the model as evidence.",
)

if st.button("Generate answer", type="primary"):
    with st.spinner("Retrieving evidence and generating an answer..."):
        try:
            data = call_answer(normalize_base_url(base_url), query, limit=limit, semantic=True)
        except Exception as exc:
            st.error(f"Answer failed: {exc}")
            st.stop()

    retrieval = data.get("retrieval") or {}
    if retrieval.get("degraded_to_lexical_only"):
        st.warning(
            "Semantic retrieval was unavailable, so the evidence below came from keyword "
            f"search alone. Reason: {retrieval.get('semantic_error')}"
        )

    st.subheader("Answer")
    if data.get("generated_by") == "local_fallback":
        st.error(
            "This text was NOT produced by a language model. The generation provider failed "
            f"({data.get('generation_error')}) and the system returned its built-in fallback, "
            "which carries no citations and must not be treated as an answer."
        )
    elif data.get("generated_by") == "model":
        st.caption(f"Generated by {data.get('model')}")

    st.write(data.get("answer") or "_The answer endpoint returned no text._")

    citations = data.get("citations") or []
    st.subheader(f"Citations ({len(citations)})")
    if not citations:
        st.info("No citations were returned. Every legal proposition should carry one.")
    for citation in citations:
        node_id = citation.get("node_id", "")
        st.markdown(
            f"**{citation.get('title') or node_id}** — "
            f"{citation.get('authority_class') or 'unclassified'}"
            f"{f' · {citation.get(chr(39) + chr(39))}' if False else ''}"
        )
        st.caption(f"`{node_id}` · locator {citation.get('locator') or 'n/a'}")
        if citation.get("url"):
            st.caption(citation["url"])

    with st.expander("Evidence and retrieval trace"):
        if retrieval:
            st.json(
                {
                    "profile": retrieval.get("profile"),
                    "profile_fingerprint": retrieval.get("profile_fingerprint"),
                    "lexical_candidates": retrieval.get("lexical_candidates"),
                    "semantic_candidates": retrieval.get("semantic_candidates"),
                    "graph_expanded_nodes": retrieval.get("graph_expanded_nodes"),
                    "duplicates_removed": retrieval.get("duplicates_removed"),
                }
            )
        for evidence in (data.get("evidence") or [])[:20]:
            st.write(evidence)
